"""Advisory ORM model."""

import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, ForeignKey, Index, Text, func
from sqlalchemy.orm import mapped_column, Mapped, relationship
from app.database import Base
from app.models.base import UUIDMixin


class Advisory(Base, UUIDMixin):
    """Weather-based advisories generated by the advisory engine."""
    __tablename__ = "advisories"

    location_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("locations.id", ondelete="CASCADE"), nullable=False
    )
    alert_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("alerts.id", ondelete="SET NULL"), nullable=True
    )
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    # agriculture | travel | outdoor | general

    recommendation: Mapped[str] = mapped_column(Text, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    location: Mapped["Location"] = relationship(back_populates="advisories")  # noqa: F821
    alert: Mapped["Alert | None"] = relationship(back_populates="advisories")  # noqa: F821

    __table_args__ = (
        Index("ix_advisories_location_category", "location_id", "category"),
    )

    def __repr__(self) -> str:
        return f"<Advisory category={self.category} location={self.location_id}>"
