"""Alert and AlertPreference ORM models."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING
from sqlalchemy import String, Float, Boolean, DateTime, ForeignKey, Index, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import mapped_column, Mapped, relationship
from app.database import Base
from app.models.base import UUIDMixin, TimestampMixin

if TYPE_CHECKING:
    from app.models.user import User, UserLocation
    from app.models.location import Location
    from app.models.advisory import Advisory


class Alert(Base, UUIDMixin, TimestampMixin):
    """Weather alerts generated by the rule-based alert engine or external feeds."""
    __tablename__ = "alerts"

    location_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("locations.id", ondelete="CASCADE"), nullable=False
    )
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # e.g. heavy_rain | extreme_heat | strong_wind | thunderstorm | high_humidity

    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    # low | medium | high | critical

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    message: Mapped[str | None] = mapped_column(Text, nullable=True)  # AI summary or voice-ready alert text
    weather_context: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    triggered_value: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    threshold_value: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Relationships
    location: Mapped["Location"] = relationship(back_populates="alerts")  # noqa: F821
    advisories: Mapped[list["Advisory"]] = relationship(back_populates="alert")  # noqa: F821

    __table_args__ = (
        Index("ix_alerts_location_active", "location_id", "is_active"),
    )

    def __repr__(self) -> str:
        return f"<Alert {self.alert_type} severity={self.severity} active={self.is_active}>"


# Alias for WeatherAlert
WeatherAlert = Alert


class AlertPreference(Base, UUIDMixin, TimestampMixin):
    """User-specific alert thresholds and subscription preferences."""
    __tablename__ = "alert_preferences"

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    location_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("user_locations.id", ondelete="CASCADE"), nullable=True, index=True
    )
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)  # rain | temp_high | wind | humidity
    threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    enabled: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    user: Mapped["User"] = relationship(back_populates="alert_preferences")
    location: Mapped["UserLocation | None"] = relationship(back_populates="alert_preferences")

    __table_args__ = (
        UniqueConstraint("user_id", "location_id", "alert_type", name="uq_alert_preferences_user_loc_type"),
        Index("ix_alert_preferences_user_enabled", "user_id", "enabled"),
    )

    def __repr__(self) -> str:
        return f"<AlertPreference user={self.user_id} type={self.alert_type} enabled={self.enabled}>"
