"""initial schema

Revision ID: 1d9e5f865329
Revises: 
Create Date: 2026-09-10 18:51:04.167849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d9e5f865329'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('weather_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_history_session_created', 'chat_history', ['session_id', 'created_at'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_lat_lon', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_locations_name', 'locations', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_location_active', 'alerts', ['location_id', 'is_active'], unique=False)
    op.create_table('forecasts',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_type', sa.String(length=10), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecasts_location_type_for', 'forecasts', ['location_id', 'forecast_type', 'forecast_for'], unique=False)
    op.create_table('weather_data',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('feels_like_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Integer(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Integer(), nullable=True),
    sa.Column('condition_code', sa.Integer(), nullable=True),
    sa.Column('condition_text', sa.String(length=255), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('rain_probability_pct', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_data_location_fetched', 'weather_data', ['location_id', 'fetched_at'], unique=False)
    op.create_table('advisories',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advisories_location_category', 'advisories', ['location_id', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_advisories_location_category', table_name='advisories')
    op.drop_table('advisories')
    op.drop_index('ix_weather_data_location_fetched', table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index('ix_forecasts_location_type_for', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_alerts_location_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_locations_name', table_name='locations')
    op.drop_index('ix_locations_lat_lon', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_chat_history_session_created', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
